### PR TITLE
Try to improve lidar static tf publishing #102

### PR DESCRIPTION
**Pull request by SijmenHuizenga**

### CODE REVIEW

**Comment by davidoort** [comment]
This is based off of the master branch which had a cones bug. I have tried to create a patch file and to apply it to this branch https://github.com/FS-Online/Formula-Student-Driverless-Simulator/pull/112 but it didn't work

**Comment by davidoort** [comment]
Can we rebase this?

**Comment by SijmenHuizenga** [comment]
Let's hold off on this until #112 is finished and merged.

**Comment by SijmenHuizenga** [comment]
There has been no progress on this because it is not important at all. Closing to keep github pr's clean.

**Pull request closed without merging**
